var strings = {
    "MONDAY": "Понеділок",
    "TUESDAY": "Вівторок",
    "WEDNESDAY": "Середа",
    "THURSDAY": "Четвер",
    "FRIDAY": "П'ятниця",
    "SATURDAY": "Субота",
    "SUNDAY": "Неділя",
    "EDIT": "Редагування",
    "NEW": "Створення",
    "ALWAYS": "Завжди",
    "ODD_WEEK": "Непарний тиждень",
    "EVEN_WEEK": "Парний тиждень",
    "MIXED": "Змішана",
    "LECTURE": "Лекція",
    "PRACTICE": "Практика",
    "UNKNOWN": "Невідомо",
    "PASS_FAIL": "Залік",
    "EXAM": "Екзамен",
    "NOTHING": "Нічого"
};